# Generated by Django 5.1.4 on 2024-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='behance_link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='dribbble_link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="Email address for the 'Say Hello' section.", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='first_image_2x',
            field=models.ImageField(blank=True, help_text='Upload the high-resolution (2x) version of the first image.', null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='first_image_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the first image.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_link',
            field=models.URLField(blank=True, help_text='LinkedIn Profile URL', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Telegram Contact URL', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='WhatsApp Contact URL', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='x_link',
            field=models.URLField(blank=True, help_text='X (Twitter) Profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Instagram Profile URL', null=True),
        ),
    ]
