# Generated by Django 5.1.4 on 2024-12-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_sitesettings_behance_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='recent_work_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='recent_work_title',
            field=models.CharField(default='Recent Works', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='say_hi_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='say_hi_title',
            field=models.CharField(default='Recent Works', max_length=100),
        ),
    ]
